server:
  port: 8081
  
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:log4jdbc:postgresql://192.168.100.96:5432/forwiz_learn_db
    username: myuser
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet: # 파일업로드 추가
    multipart:
      file-size-threshold: 1MB
      location: C:/img
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
com:
 learn:
   forwiz:
     client:
       path: C:/thumbnail_image